name: LLM Ops

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag (e.g. v1.0.0)"
        required: true
        type: string
        default: "v1.0.0"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  # unit-test:
  #   needs: checkout
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: 1.2.4

  #     - name: Install Dependencies
  #       run: bun install

  #     - name: Run Unit Tests
  #       run: bun run test

  build:
    # needs: [unit-test, checkout]
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "Leslie"
          git config --global user.email "lesliechueng1996@icloud.com"

      - name: Create Release Tag
        run: |
          NEW_TAG="${{ github.event.inputs.tag }}"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "Created and pushed release tag: $NEW_TAG"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.event.inputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
